### ISSUE TITLE
backend & database 관련 내용 학습

### ISSUE THREAD

**Issue by anaclumos** [woowa-techcamp-2020/hkb-7#2]
## 이슈 요약

backend & database 관련 내용 학습 이슈입니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] BE - mysql 및 backend DB boilerplate
    - [ ] 프로젝트에 도입할 수 있는 전반적인 DB 파일 구조 공부하기
- [ ] BE - ERD의 주요 개념 이해 및 SQL 쿼리 생성
- [ ] BE - passport 및 passport-local
- [ ] BE - DB에 들어갈 테이블, 필드에 대한 고민과 학습

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

- [todo-7 줌코딩님 코드](https://github.com/woowa-techcamp-2020/todo-7)

**Comment by younho9** [comment]
study 관련 이슈는 닫도록 하겠습니다..!
