### ISSUE TITLE
데이터베이스 모델링

### ISSUE THREAD

**Issue by younho9** [woowa-techcamp-2020/hkb-7#8]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

요구사항을 분석하고 데이터베이스를 설계합니다.

## 작업의 크기

> 대략적인 작업의 크기와 난이도를 수치로 표현합니다. ex) 2.5/5 

🌶

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] ERD 그리기
- [ ] 데이터베이스 테이블 그리기

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [lucas - BE-ERD](https://lucas.codesquad.kr/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BA%A0%ED%94%842020/course/%EC%9B%B9%ED%92%80%EC%8A%A4%ED%83%9D/WEEK-5-%EA%B0%80%EA%B3%84%EB%B6%80(1-2)/BE-ERD)

**Comment by anaclumos** [comment]
User Profile 테이블을 분리하는 것은 어떨까요? First name, Last Name, Profile Picture 같은 것들이요.
